# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0002_auto_20180306_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pic',
            new_name='pic_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_posted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
