# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inst', '0003_auto_20180306_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pic_id',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
